#!/bin/sh
set -e
echo "Running pre-push checks..."
echo '+cargo clippy --all-targets --all-features -- -D warnings'
cargo clippy --all-targets --all-features -- -D warnings
echo '+cargo audit'
cargo audit
